apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-yzrkhldf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-yzrkhldf 
  name: go-yzrkhldf
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-yzrkhldf
    weight: 100 
